// File: AITermsOfUse.jsx
import React from 'react';
import Footer from '../Footer';
import Header from '../Header';

const aiTermsSections = [
  {
    title: 'AI Terms of Use – SynchMate',
    content:
      'These Terms govern your use of any artificial intelligence features, tools, products, or integrations made available in or through SynchMate and related PathSynch properties (“AI Functionality”). By using the AI Functionality, you confirm you’ve read, understood, and agree to these Terms, and that you are of legal age and authority to accept them on behalf of yourself or your organization.',
  },
  {
    title: '1. Definitions',
    content:
      '“AI Functionality” means all SynchMate AI features (e.g., chat/agents, automations, phone/voice interactions) available in our products and websites. “Input” means any content or data you or your end users submit into the AI Functionality. “Output” means content or data returned or generated by the AI Functionality as a result of your Input.',
  },
  {
    title: '2. Agreement by Use',
    content:
      'Using any AI Functionality constitutes acceptance of these Terms. If you use the AI Functionality on behalf of an employer or organization, you represent that you are authorized to bind that party to these Terms.',
  },
  {
    title: '3. Input and Output',
    content:
      'You are responsible for Input (including ensuring you have all rights and permissions). You may use Output for lawful purposes under these Terms, but you may not sell, license, or redistribute Output as your own product without our prior written consent.',
  },
  {
    title: '4. Acknowledgements & Grants',
    content:
      'You acknowledge that AI is not human and that interactions may be recorded to operate and improve services. SynchMate may use trusted third-party providers (“Providers”) to deliver AI Functionality. Providers may process Input and Output in locations of their choosing. You grant SynchMate a royalty-free license to use Input and Output as needed to provide and support the AI Functionality, including allowing Providers to process such data.',
  },
  {
    title: '5. Use Restrictions',
    content:
      'You must comply with all applicable laws, including privacy and intellectual property laws. Prohibited uses include impersonation, voice cloning without consent, reverse engineering, and any activity restricted by these Terms or applicable law. We may suspend or terminate access, or remove/disable agents or features, at our discretion for violations.',
  },
  {
    title: '6. Data Use & Privacy',
    content:
      'You are solely responsible for any data you collect from third parties via AI agents or forms. SynchMate may access and use Input, Output, and related data to provide support, protect users, secure systems, and meet legal obligations. We do not sell or rent your personal information. Additional details appear in our Privacy Policy.',
  },
  {
    title: '7. Term & Termination',
    content:
      'Your right to use the AI Functionality lasts while your applicable subscription is active. We may suspend or terminate access immediately for a material breach of these Terms.',
  },
  {
    title: '8. No Warranties',
    content:
      'AI Functionality is provided “as is.” SynchMate disclaims all implied warranties, including merchantability, fitness for a particular purpose, and non-infringement, to the maximum extent permitted by law. Output may be incorrect, misleading, or incomplete; do not rely on it for professional advice.',
  },
  {
    title: '9. No Refunds',
    content:
      'Refunds are not issued for AI-related add-ons (e.g., AI agent phone numbers) unless required by law.',
  },
  {
    title: '10. Questions',
    content:
      'If you have questions about these Terms or the AI Functionality, please contact our support team.',
  },
];

const AITermsOfUse = () => {
  return (
    <div className="bg-green">
      <Header />
      <div className="privacy-policy">
        <h2 className="privacy-title">SynchMate — AI Terms of Use</h2>
        <p className="policy-text" style={{ marginTop: 8 }}>
          Last updated: {new Date().toLocaleDateString()}
        </p>
        <div className="policy-content">
          {aiTermsSections.map((section, index) => (
            <div className="policy-section" key={index}>
              <h3 className="policy-heading">{section.title}</h3>
              <p className="policy-text">{section.content}</p>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default AITermsOfUse;